Adding data from human evaluation
wmt-conference/wmt23-news-systems pull request #3
Opened 2024-03-12 00:38 UTC by kocmitom

2024-03-12 09:45 UTC, snukky requested changes
I think we can keep only results.txt & scores_all.csv, and add `scripts/rm_bad_docs.py` with the following instructions:

`cat scores_all.csv | scripts/rm_bad_docs.py | grep -v ",True," > scores_noqc_nodoc.csv`

2024-03-12 09:45 UTC, snukky commented on humaneval/DA+SQM/WMT23.results.noqc_nodocs.txt
No need to publish this file, it should be the same as results.txt.

2024-03-12 09:45 UTC, snukky commented on humaneval/DA+SQM/WMT23.scores_noqc.csv
No need to publish this file, better to publish `scripts/rm_bad_docs.py`, which will give you this file from scores_all.csv

2024-03-12 09:45 UTC, snukky commented on humaneval/DA+SQM/WMT23.scores_noqc_nodocs.csv
No need to publish this file, it's just `grep -v ",True,"`

2024-03-12 09:45 UTC, snukky commented on humaneval/DA+SQM/WMT23.results.txt
We can publish this file, but it may be better to provide output from a script that will be provided as well, instead of from the Appraise script.

2024-03-12 09:45 UTC, snukky commented on humaneval/DA+SQM/WMT23.unreliable_annotators.txt
No need to publish this file, scores_all.csv has them excluded already.

2024-03-12 11:46 UTC, kocmitom commented
I have removed the necessary files and added the scripts and brief readme with the cleanup code

2024-03-13 10:46 UTC, snukky commented on humaneval/DA+SQM/README.md
> +cat scores_all.csv | scripts/rm_bad_docs.py | grep -v ",True," > scores_noqc_nodoc.csv
```suggestion
cat scores_all.csv | python3 scripts/rm_bad_docs.py | grep -v ",True," > scores_noqc_nodoc.csv

```

2024-03-13 10:48 UTC, snukky commented on humaneval/DA+SQM/CSV-format.md
> +Please reach out to `{chrife,rogrundk}@microsoft.com` for any questions you may have.
```suggestion
```

2024-03-13 10:50 UTC, merged